### ISSUE TITLE
Gumps Don't Open

### ISSUE THREAD

**Issue by Kalan-Brock** [xrunuo/xrunuo#2]
Guild gump, help gump, etc don't open in-game.

**Comment by ppardalj** [comment]
@Kalan-Brock can you provide more info about your environment? OS version, .NET framework.

I am running Windows NT 5.1.2600 SP3 with .NET Framework 4.0.30319.1 and works properly for me. Are you getting any error in the console? Are you sure you have proper zlib.dll version in your server root directory? Make sure you have zlib32.dll or zlib64.dll depending on your OS version.
