### ISSUE TITLE
Running server on mac with docker

### ISSUE THREAD

**Issue by lucasrencoret** [xrunuo/xrunuo#6]
Tried to make `make docker-run` and received this error:

```
ScriptCompiler: Error: compilation failed (1 errors, 0 warnings)
Errors: ../Scripts/RestApi/Core/Request.cs:
    CS1644: Line 25: Feature 'declaration expression' cannot be used because it is not part of the C# 6.0 language specification
Core: Fatal: Compilation failed. Press any key to exit.
```

docker version 19.03.8
macOS Catalina Version 10.15.4

![Screen Shot 2020-05-03 at 23 06 14](https://user-images.githubusercontent.com/9797677/80933676-c058ad00-8d92-11ea-9613-959c194be98a.png)

**Comment by PabloBenigno** [comment]
Hello! It's a feature dropped in C# 6, so you need to compile it with an older version of the language.

Sorry, this has become legacy long time ago :)

**Comment by lucasrencoret** [comment]
which version of mono should be ok?

**Comment by lucasrencoret** [comment]
I've tried this couple of days with different versions of Mono, but I can't compile it successfully. 

I've tried using c# 6.0, but neither..
```c#
<LangVersion>7.1</LangVersion>
```

Tried using other version of .NET and neither.
```c#
<Project ToolsVersion="4.0" ....
```
Please could you help me with the combination? Thanks!

**Comment by PabloBenigno** [comment]
We used VS2010 by that time, so I guess C# version was 4, try that :)

**Comment by lucasrencoret** [comment]
I'm trying to change the `LangVersion` to 4 in `RestApi.csproj`, `Server.csproj`, `Distro.csproj`.

Apparently it's not working because I'm receiving similar errors (running it with older versions of mono). `/opt/xrunuo/Server/Timer/Timer.cs(252,12): error CS1056: Unexpected character '$'`

Am I missing the `LangVersion` somewhere else?

**Comment by lucasrencoret** [comment]
All the code was written in C# 4.0? Looking out for answers got this:

```
The $ string interpolation symbol is only available in C# 6+. Make sure that you are compiling with C#6. C#6 is supported in MSBuild 14.0+.
```

**Comment by PabloBenigno** [comment]
You're completely right, and that makes me think part was rewritten. Let me ask.

**Comment by ppardalj** [comment]
Hi @lucasrencoret , thanks for opening this issue.

I just pushed a commit (https://github.com/xrunuo/xrunuo/commit/d9beb8cb09cae392ae7f75a9e646c3196b44dbc2) with a fix to allow compilation in the docker image by removing this C# 6 feature that was being used. I just tested it and it works.

Please let us know if you have further issues!

**Comment by lucasrencoret** [comment]
@ppardalj Thanks!

Now I'm receiving this error:

![Screen Shot 2020-05-07 at 09 57 39](https://user-images.githubusercontent.com/9797677/81303061-35eda300-9049-11ea-9fc2-2b372d257d56.png)

`TileData: Fatal: TileData.mul was not found. Make sure your x-runuo.xml is properly configured.`

**Comment by PabloBenigno** [comment]
You must place the mul files from the UO client on the configured folder. As far as I know we don't provide those files in the repository, as they come with the UO client.

**Comment by lucasrencoret** [comment]
Placed the mul files in the directory and worked. Thanks!

Now I'm trying to access the server, with the `127.0.0.1` or the `172.17.0.2`, but neither worked. How can I access the server?

Is it cause this problem? `Got a bad hardware address length for an AF_PACKET 16 8`

**Comment by ppardalj** [comment]
That's weird. TBH I haven't tried this in docker, I would need to take a look.

**Comment by ppardalj** [comment]
I have submitted a PR that adds support for .NET Core, so Docker should no longer be needed to run XRunUO on OSX. Could you please check it out guys? @PabloBenigno @lucasrencoret 

Here it is: https://github.com/xrunuo/xrunuo/pull/7

**Comment by ppardalj** [comment]
I'm closing this issue since OSX support is already covered by .NET Core, and we don't plan to add docker support in the near future. If you still want this feature I encourage you to submit a PR! :)

Thank you for your collaboration!
